services:
    cdek:
        class: Lopatinas\CdekBundle\Service\CdekService
        calls:
            - [setAccount, ["%cdek.account%"]]
            - [setPassword, ["%cdek.password%"]]
            - [init, []]